### ISSUE TITLE
ros-kinetic-flydra error

### ISSUE THREAD

**Issue by llorban** [strawlab/strawlab-ansible-roles#2]
ros-kinetic-flydra task produces the following error: 
* * *
TASK [ros-kinetic-flydra : install rosinstall command] *************************
fatal: [localhost]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'python-rosinstall'' failed: E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/p/python-rosinstall/python-rosinstall_0.7.8-1_all.deb  Could not resolve 'packages.ros.org'\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr": "E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/p/python-rosinstall/python-rosinstall_0.7.8-1_all.deb  Could not resolve 'packages.ros.org'\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  python-rosinstall\n0 upgraded, 1 newly installed, 0 to remove and 173 not upgraded.\nNeed to get 23.7 kB of archives.\nAfter this operation, 163 kB of additional disk space will be used.\nErr:1 http://packages.ros.org/ros/ubuntu xenial/main i386 python-rosinstall all 0.7.8-1\n  Could not resolve 'packages.ros.org'\nErr:1 http://packages.ros.org/ros/ubuntu xenial/main i386 python-rosinstall all 0.7.8-1\n  Could not resolve 'packages.ros.org'\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  python-rosinstall", "0 upgraded, 1 newly installed, 0 to remove and 173 not upgraded.", "Need to get 23.7 kB of archives.", "After this operation, 163 kB of additional disk space will be used.", "Err:1 http://packages.ros.org/ros/ubuntu xenial/main i386 python-rosinstall all 0.7.8-1", "  Could not resolve 'packages.ros.org'", "Err:1 http://packages.ros.org/ros/ubuntu xenial/main i386 python-rosinstall all 0.7.8-1", "  Could not resolve 'packages.ros.org'"]}

PLAY RECAP *********************************************************************
localhost                  : ok=26   changed=20   unreachable=0    failed=1

**Comment by llorban** [comment]
packages.ros.org loads fine in the browser

**Comment by llorban** [comment]
rerunning the installer produces the same error.

**Comment by llorban** [comment]
worked on the third attempt

**Comment by astraw** [comment]
Our lab continuous integration server runs this recipe every morning and had no trouble for the last weeks and the URLs work fine from here. Is the browser you're testing from running on the same machine where the ansible recipe is running? Could your machine be behind a proxy that would block access?

**Comment by llorban** [comment]
The strange thing was that I could reach packages.ros.org from the same pc via the browser just fine, but the installer would fail. Running it on the third time installed okay.
