### ISSUE TITLE
roslaunch fails

### ISSUE THREAD

**Issue by llorban** [strawlab/strawlab-ansible-roles#3]
running roslaunch fails with the following error: 

roslaunch freemovr_engine demo_display_server.launch

RuntimeError: Assertion error (gc.valid()) at /home/flightlab/ros/freemovr-kinetic/src/freemovr_engine/src/dsosg.cpp(909): could not create a graphics context with your desired traits
[display_server_demo-2] process has died [pid 66312, exit code -11, cmd /home/flightlab/ros/freemovr-kinetic/devel/lib/freemovr_engine/display_server --mode overview __name:=display_server_demo __log:=/home/flightlab/.ros/log/45166450-d095-11e7-b057-000c2924f9d0/display_server_demo-2.log].
log file: /home/flightlab/.ros/log/45166450-d095-11e7-b057-000c2924f9d0/display_server_demo-2*.log

There is one PC display connected to this computer.

**Comment by astraw** [comment]
This is a bug with freemovr_engine, not with this project. I re-filed this issue as https://github.com/strawlab/freemovr_engine/issues/9 and I am closing this issue here.
